model_name: QWen2-VL
model_path: Qwen/Qwen2-VL-7B-Instruct
save_path: /root/autodl-tmp/hallscope/VQAIDK/train_qwen

dataset: VQAIDK
annotation_path: /home/hallscope/data/VQAIDK/VQA_IDK.json
data_folder: /root/autodl-fs/coco_images/train
return_logits: False
batch_size: 1
image_shape: "640,480"
num_samples: 5000
