model_name: QWen2-VL
model_path: Qwen/Qwen2-VL-7B-Instruct
save_path: /root/autodl-tmp/hallscope/VQA/train_qwen

dataset: VQA
annotation_path: /home/hallscope/data/VQA/v2_train.json
data_folder: /root/autodl-fs/coco_images/train
split: train
batch_size: 1
image_shape: "640,480"
num_samples: 5000
