model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: /root/autodl-tmp/hallscope/VQA/testing

dataset: VQA
annotation_path: /home/hallscope/data/VQA/v2_train.json
data_folder: /root/autodl-fs/coco_images/train
split: train
prompt: oe
theme: general
batch_size: 8
image_shape: "640,480"
num_samples: 20000
