model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: /root/autodl-fs/hallscope/ScienceQA/train

dataset: ScienceQA
split: train
prompt: oe
theme: general
batch_size: 8
num_samples: 5000

temperature: 0.0
top_p: 0.9
num_beams: 1