model_name: LLaMa-7B
model_path: /root/autodl-tmp/llama2-7b-chat
save_path: ./output/trivia_qa
split: SD_TYPO
dataset: trivia_qa
prompt: concisely
theme: QA
num_chunks: 1
chunk_idx: 0
temperature: 0.0
top_p: 0.9
num_beams: 1
num_samples: 1000