model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: /root/autodl-fs/hallscope/AOKVQA/train

dataset: AOKVQA
annotation_path: /home/hallscope/data/AOKVQA/aokvqa_v1p0_train.json
data_folder: /root/autodl-fs/coco2017/coco2017/train2017
split: train
prompt: oe
theme: general
batch_size: 1
num_samples: 10000
