model_name: LLaVA-7B
model_path: /root/autodl-fs/llava-1.5-7b-hf
save_path: /root/autodl-tmp/hallscope/pope/popular/multi/train

dataset: POPE
annotation_path: /home/hallscope/data/pope/coco_train/coco_train_pope_popular.jsonl
data_folder: /root/autodl-fs/coco_images/train
split: train
prompt: oe
theme: general
category: popular
image_shape: "640,480"
num_samples: 5000
batch_size: 2
n_multi_gene: 6
return_logits: True