model_name: LLaVA
model_path: llava-hf/llava-v1.6-mistral-7b-hf
save_path: /root/autodl-fs/hallscope/pope/adversarial/llava

dataset: POPE
annotation_path: /home/hallscope/data/pope/coco_train/coco_train_pope_adversarial.jsonl
data_folder: /root/autodl-fs/coco_images/train
num_samples: 2000
batch_size: 1
