model_name: QWen2-VL
model_path: Qwen/Qwen2-VL-7B-Instruct
save_path: /root/autodl-tmp/hallscope/pope/popular/train

dataset: POPE
annotation_path: /home/hallscope/data/pope/coco_train/coco_train_pope_popular.jsonl
data_folder: /root/autodl-fs/coco_images/train
num_samples: 10000
batch_size: 1
