model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: ./output/pope

split: train
dataset: POPE
annotation_path: ./data/pope/coco_train/coco_train_pope_popular.jsonl
prompt: oe
theme: general
temperature: 0.0
top_p: 0.9
num_beams: 1