model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: ./output/pope

dataset: POPE
annotation_path: /home/hallscope/data/pope/coco_val/coco_val_pope_popular.json
data_folder: /root/autodl-fs/coco_images/val
split: val
prompt: oe
theme: general
category: popular

temperature: 0.0
top_p: 0.9
num_beams: 1