model_name: QWen2-VL
model_path: Qwen/Qwen2-VL-7B-Instruct
save_path: /root/autodl-tmp/hallscope/ChartVQA/train

dataset: ChartVQA
annotation_path: /root/autodl-tmp/ChartVQA/train/train_augmented.json
data_folder: /root/autodl-tmp/ChartVQA/train/png
split: train
prompt: oe
theme: general
batch_size: 1
num_samples: 20000
