model_name: LLaVA-7B
model_path: /root/autodl-tmp/llava-1.5-7b-hf
save_path: /root/autodl-tmp/hallscope/ChartVQA/train

dataset: ChartVQA
annotation_path: /root/autodl-tmp/ChartVQA/train/train_augmented.json
data_folder: /root/autodl-tmp/ChartVQA/train/png
split: train
prompt: oe
theme: general
batch_size: 1
num_samples: 15000
